# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["main"]
        paths:
            - "package.json"

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    # Single deploy job since we're just deploying
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@main
            - name: Check if version bumped
              id: version_check
              run: |
                  git fetch origin ${{ github.ref }} --depth=2
                  PREV_VERSION=$(git show HEAD^:package.json | jq -r .version)
                  CURR_VERSION=$(jq -r .version package.json)
                  echo "Previous version: $PREV_VERSION"
                  echo "Current version: $CURR_VERSION"
                  if [ "$PREV_VERSION" = "$CURR_VERSION" ]; then
                    echo "No version bump detected. Skipping workflow."
                    exit 78
                  fi
            - name: Set up Node
              uses: actions/setup-node@main
              with:
                  node-version: 22
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build && cp ./dist-react/index.html ./dist-react/404.html
            - name: Setup Pages
              uses: actions/configure-pages@main
            - name: Upload artifact
              uses: actions/upload-pages-artifact@main
              with:
                  # Upload dist folder
                  path: "./dist-react"
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@main
